* Rose-Hulman AI XPrize Data Pipeline
** Introduction
IBM is holding an AI XPrize competition that our school, Rose-Hulman
Institute of Technology, is participating in. Details on the
competition are found here: http://ai.xprize.org, and information
about the vision for the finished product can be found here:
https://wordpress.rose-hulman.edu/ai-group/.

This project is intended to allow for the usage of different AI
components across different languages and possibly even machines all
linked together using [[uima.apache.org][UIMA]], the Unstructured Information Management
Architecture.

The program communicates with the robot using [[ros.org][ROS]], the robotic
operating system, and will be in charge of processing the data sent to
it by the robot's sensors and sending abstract commands for the robot
to execute.
** Dependencies
- Java 1.8
- ROS Indigo
- UIMA
- Gradle
- ROSJava
** Installation
This repository is a ROS package, and as such should be cloned into
your =catkin_ws/src= folder (see [[http://wiki.ros.org/catkin/Tutorials/create_a_workspace][this tutorial]] for information about
setting up a workspace).

#+BEGIN_SRC bash
  cd catkin_ws/src
  git clone https://github.com/RHIT-XPrize/rhit-xprize-pipeline edu_rosehulman_aixprize

  cd ..
  catkin_make

  echo "source catkin_ws/devel/setup.bash" >> ~/.bashrc
#+END_SRC

Note that projects will be Gradle projects, and should be imported as
such.
** Usage
#+BEGIN_SRC bash
  roscore &
  rosrun edu_rosehulman_aixprize pipeline edu.rosehulman.aixprize.pipeline.core.Controller
#+END_SRC
** Troubleshooting
- ROS is unable to find the package
  + Ensure that you cloned the repository into a folder named
    =edu_rosehulman_aixprize=.
